# ============================================================
# datos/tecnologias.py
# Autor: Kevin Jiménez
# ============================================================

tecnologias = [
    {
        "nombre": "Inteligencia Artificial",
        "categoria": "automatizacion",
        "impacto_social": 9,
        "impacto_laboral": -6,
        "impacto_educacion": 9,
        "impacto_salud": 8,
        "tendencia": [3, 4, 5, 7, 9],  # adopción últimos 5 años (escala 1-10)
        "descripcion": "Sistemas computacionales que simulan la inteligencia humana.",
        "ventajas": ["Automatización de tareas repetitivas", "Diagnóstico médico mejorado",
                     "Personalización de experiencias", "Análisis de grandes volúmenes de datos"],
        "desventajas": ["Desplazamiento laboral", "Sesgos algorítmicos",
                        "Dependencia tecnológica", "Privacidad comprometida"],
        "año_auge": 2023
    },
    {
        "nombre": "Redes Sociales",
        "categoria": "comunicacion",
        "impacto_social": 6,
        "impacto_laboral": 5,
        "impacto_educacion": 4,
        "impacto_salud": -4,
        "tendencia": [8, 9, 8, 7, 6],
        "descripcion": "Plataformas digitales de conexión e intercambio de información.",
        "ventajas": ["Comunicación global instantánea", "Movimientos sociales",
                     "Marketing y emprendimiento", "Acceso a información"],
        "desventajas": ["Desinformación", "Adicción digital",
                        "Impacto en salud mental", "Polarización social"],
        "año_auge": 2010
    },
    {
        "nombre": "Internet de las Cosas (IoT)",
        "categoria": "automatizacion",
        "impacto_social": 7,
        "impacto_laboral": 6,
        "impacto_educacion": 6,
        "impacto_salud": 7,
        "tendencia": [2, 3, 5, 6, 7],
        "descripcion": "Red de dispositivos físicos conectados a internet que recopilan datos.",
        "ventajas": ["Hogares inteligentes", "Eficiencia energética",
                     "Monitoreo de salud", "Ciudades inteligentes"],
        "desventajas": ["Vulnerabilidades de seguridad", "Privacidad de datos",
                        "Obsolescencia rápida", "Dependencia digital"],
        "año_auge": 2018
    },
    {
        "nombre": "Blockchain",
        "categoria": "seguridad",
        "impacto_social": 6,
        "impacto_laboral": 4,
        "impacto_educacion": 5,
        "impacto_salud": 3,
        "tendencia": [1, 3, 6, 5, 6],
        "descripcion": "Tecnología de registro descentralizado e inmutable de transacciones.",
        "ventajas": ["Transparencia en transacciones", "Descentralización financiera",
                     "Contratos inteligentes", "Seguridad de datos"],
        "desventajas": ["Alto consumo energético", "Complejidad técnica",
                        "Regulación incierta", "Escalabilidad limitada"],
        "año_auge": 2017
    },
    {
        "nombre": "Realidad Virtual y Aumentada",
        "categoria": "educacion",
        "impacto_social": 7,
        "impacto_laboral": 5,
        "impacto_educacion": 9,
        "impacto_salud": 4,
        "tendencia": [2, 3, 4, 6, 7],
        "descripcion": "Tecnologías que crean o enriquecen entornos digitales inmersivos.",
        "ventajas": ["Educación inmersiva", "Simulaciones médicas",
                     "Entretenimiento avanzado", "Entrenamiento profesional"],
        "desventajas": ["Costo elevado", "Mareos y efectos físicos",
                        "Aislamiento social", "Contenido limitado"],
        "año_auge": 2016
    },
    {
        "nombre": "Automatización Robótica",
        "categoria": "automatizacion",
        "impacto_social": 5,
        "impacto_laboral": -8,
        "impacto_educacion": 5,
        "impacto_salud": 7,
        "tendencia": [4, 5, 6, 7, 8],
        "descripcion": "Uso de robots para automatizar procesos industriales y de servicios.",
        "ventajas": ["Productividad aumentada", "Reducción de errores",
                     "Cirugías precisas", "Trabajo en entornos peligrosos"],
        "desventajas": ["Pérdida masiva de empleo", "Inversión inicial alta",
                        "Dependencia tecnológica", "Impacto social negativo"],
        "año_auge": 2020
    },
    {
        "nombre": "Computación en la Nube",
        "categoria": "educacion",
        "impacto_social": 8,
        "impacto_laboral": 7,
        "impacto_educacion": 8,
        "impacto_salud": 6,
        "tendencia": [5, 6, 7, 8, 8],
        "descripcion": "Acceso a recursos computacionales a través de internet bajo demanda.",
        "ventajas": ["Acceso universal a recursos", "Reducción de costos",
                     "Escalabilidad", "Colaboración remota"],
        "desventajas": ["Dependencia de internet", "Seguridad de datos",
                        "Costos a largo plazo", "Latencia"],
        "año_auge": 2015
    },
    {
        "nombre": "Ciberseguridad",
        "categoria": "seguridad",
        "impacto_social": 8,
        "impacto_laboral": 9,
        "impacto_educacion": 7,
        "impacto_salud": 6,
        "tendencia": [5, 6, 7, 8, 9],
        "descripcion": "Conjunto de prácticas y tecnologías para proteger sistemas digitales.",
        "ventajas": ["Protección de datos personales", "Seguridad financiera",
                     "Confianza digital", "Nuevos empleos especializados"],
        "desventajas": ["Carrera armamentista digital", "Costo elevado",
                        "Escasez de profesionales", "Evolución constante de amenazas"],
        "año_auge": 2021
    },
    {
        "nombre": "Telemedicina",
        "categoria": "salud",
        "impacto_social": 8,
        "impacto_laboral": 6,
        "impacto_educacion": 5,
        "impacto_salud": 9,
        "tendencia": [2, 3, 4, 8, 9],
        "descripcion": "Prestación de servicios médicos a distancia mediante tecnología.",
        "ventajas": ["Acceso a salud remota", "Reducción de costos",
                     "Atención inmediata", "Seguimiento de pacientes"],
        "desventajas": ["Brecha digital", "Límites del diagnóstico remoto",
                        "Privacidad médica", "Dependencia tecnológica"],
        "año_auge": 2020
    },
    {
        "nombre": "Vehículos Autónomos",
        "categoria": "transporte",
        "impacto_social": 7,
        "impacto_laboral": -5,
        "impacto_educacion": 4,
        "impacto_salud": 7,
        "tendencia": [1, 2, 3, 5, 7],
        "descripcion": "Vehículos capaces de circular sin intervención humana.",
        "ventajas": ["Reducción de accidentes", "Movilidad para discapacitados",
                     "Eficiencia energética", "Reducción de tráfico"],
        "desventajas": ["Desempleo en transporte", "Dilemas éticos",
                        "Infraestructura requerida", "Hackeo de vehículos"],
        "año_auge": 2025
    }
]
